---
kind: pipeline
type: docker
name: default

steps:
- name: cargo test
  image: rust:latest
  commands:
  - apt-get update
  - apt-get install -y libudev-dev
  - cargo build --verbose --all
  - cargo test --verbose --all